### ISSUE TITLE
Dates prior to 1900

### ISSUE THREAD

**Issue by alpha-beta-soup** [etiennesky/netcdfbrowser#1]
Trying to view a NetCDF with time extending back to 1850, I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/user/.qgis2/python/plugins\netcdfbrowser\netcdfbrowserdialog.py", line 121, in on_pbnFileName_pressed
    self.updateFile()
  File "C:/Users/user/.qgis2/python/plugins\netcdfbrowser\netcdfbrowserdialog.py", line 227, in updateFile
    self.updateVariable()
  File "C:/Users/user/.qgis2/python/plugins\netcdfbrowser\netcdfbrowserdialog.py", line 344, in updateVariable
    val = date.strftime("%Y-%m-%d %H:%M:%S")
ValueError: year=1850 is before 1900; the datetime strftime() methods require year >= 1900
```

[It is possible](http://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900) to get around this limitation. I could try if you'd like.

**Comment by etiennesky** [comment]
Hi I am on a long-term vacation, so I cannot really help but if you have a simple change and certify that it doesn't break anything, please submit a pull request and I can review. Thanks!

**Comment by etiennesky** [comment]
Hi I am on a long-term vacation, so I cannot really help but if you have a simple change and certify that it doesn't break anything, please submit a pull request and I can review. Thanks!

**Comment by etiennesky** [comment]
Hi I am on a long-term vacation, so I cannot really help but if you have a simple change and certify that it doesn't break anything, please submit a pull request and I can review. Thanks!
